# 基础镜像
FROM redis
# author
MAINTAINER bedrock

# 挂载目录
VOLUME /home/bedrock/redis
# 创建目录
RUN mkdir -p /home/bedrock/redis
# 指定路径
WORKDIR /home/bedrock/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/bedrock/redis/redis.conf
