# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER bedrock

# 挂载目录
VOLUME /home/bedrock
# 创建目录
RUN mkdir -p /home/bedrock
# 指定路径
WORKDIR /home/bedrock
# 复制jar文件到路径
COPY ./jar/bedrock-visual-monitor.jar /home/bedrock/bedrock-visual-monitor.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","bedrock-visual-monitor.jar"]