# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER bedrock

# 挂载目录
VOLUME /home/bedrock
# 创建目录
RUN mkdir -p /home/bedrock
# 指定路径
WORKDIR /home/bedrock
# 复制jar文件到路径
COPY ./jar/bedrock-modules-file.jar /home/bedrock/bedrock-modules-file.jar
# 启动文件服务
ENTRYPOINT ["java","-jar","bedrock-modules-file.jar"]